[package]
name = "tamepad"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.36" }
anyhow = "1.0"
json5 = "0.4"
serde = { version = "1.0", features = ["derive"] }
crossbeam-channel = "0.5"
input-linux = { version = "0.6", features = ["serde"] }
libc = "0.2"
